### ISSUE TITLE
Plugin error: Clean Architecture Generator threw an uncaught IncorrectOperationException

### ISSUE THREAD

**Issue by sabergeek** [alvaromarco/CleanArchitecturePlugin#6]
Hi there,

I get the following IntelliJ error after hitting the "Generate" button. I've followed the setup instructions as provided. On Android Studio 2.3.2. Windows 10.

> package com.util;
> public utilscleanarch Constants { }
> com.intellij.util.IncorrectOperationException: This template did not produce a Java class or an interface
> /*
>  * Created by Android Studio.
>  * User: RAJ
>  * Date: 5/21/2017
>  * Time: 7:11 PM
>  */
> package com.util;
> public utilscleanarch Constants { }
> 	at com.intellij.ide.fileTemplates.JavaCreateFromTemplateHandler.createClassOrInterface(JavaCreateFromTemplateHandler.java:50)
> 	at com.intellij.ide.fileTemplates.JavaCreateFromTemplateHandler.createFromTemplate(JavaCreateFromTemplateHandler.java:106)
> 	at com.intellij.ide.fileTemplates.FileTemplateUtil.lambda$null$2(FileTemplateUtil.java:340)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
> 	at com.intellij.ide.fileTemplates.FileTemplateUtil.lambda$createFromTemplate$3(FileTemplateUtil.java:338)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:122)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
> 	at com.intellij.ide.fileTemplates.FileTemplateUtil.createFromTemplate(FileTemplateUtil.java:338)
> 	at com.intellij.ide.fileTemplates.FileTemplateUtil.createFromTemplate(FileTemplateUtil.java:272)
> 	at com.intellij.psi.impl.file.JavaDirectoryServiceImpl.createClassFromTemplate(JavaDirectoryServiceImpl.java:144)
> 	at com.intellij.psi.impl.file.JavaDirectoryServiceImpl.createClassFromTemplate(JavaDirectoryServiceImpl.java:119)
> 	at com.intellij.psi.impl.file.JavaDirectoryServiceImpl.createClass(JavaDirectoryServiceImpl.java:66)
> 	at architecture.components.util.UtilController.lambda$createArchitecture$1(UtilController.java:57)
> 	at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:185)
> 	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:167)
> 	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
> 	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:113)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
> 	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
> 	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:83)
> 	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:187)
> 	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:174)
> 	at architecture.components.util.UtilController.createArchitecture(UtilController.java:58)
> 	at architecture.EntityBase.create(EntityBase.java:54)
> 	at FormCreation.lambda$new$0(FormCreation.java:48)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:627)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by sabergeek** [comment]
@alvaromarco I cleared the android studio cache and the plugin worked!
